name:                blog-backend
version:             0.1.0.0
github:              "githubuser/blog-backend"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/backend#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.5.6.0
- bytestring >= 0.10.12.0
- clientsession >= 0.9.1.2
- conduit >= 1.3.4.1
- containers >= 0.6.2.1
- cryptonite >= 0.28
- memory >= 0.15.0
- mtl >= 2.2.2
- optics >= 0.4
- servant >= 0.18.2
- servant-server >= 0.18.2
- servant-auth >= 0.4.0.0
- servant-auth-server >= 0.4.6.0
- stm >= 2.5.0.0
- wai
- warp

library:
  source-dirs: src

executables:
  blog-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog-backend

tests:
  blog-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog-backend
